name: EventFinder
version: ${project.version}
main: com.tomacheese.eventfinder.Main
api-version: 1.16
commands:
  event:
    description: イベントの表示・非表示の条件を変更します
    usage: /event load | /event save | /event show | /event add PATTERN... | /event remove PATTERN...
    permission: Protecter.basic
    permission-message: You don't have <permission>
    default: op