name: EventFinder
version: ${project.version}
main: com.tomacheese.eventfinder.Main
author: mine_book000
commands:
  event:
    description: Change the conditions for showing / hiding events
    default: op