name: Multiple Version Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

jobs:
  get-versions:
    name: Get versions
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.versions.outputs.value }}

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 semver

      - name: Get versions
        id: versions
        run: |
          VERSIONS=`python tools/get-versions.py`
          echo $VERSIONS
          echo "value=${VERSIONS}" >> $GITHUB_OUTPUT

  build:
    name: Build (${{ fromJson(matrix.versions).version }})
    runs-on: ubuntu-latest
    needs: [get-versions]

    strategy:
      fail-fast: false
      matrix:
        versions: ${{ fromJson(needs.get-versions.outputs.versions) }}

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 semver

      - name: Manage matrix
        id: manage-matrix
        run: |
          echo "groupId=${{ fromJson(matrix.versions).groupId }}" | tee -a $GITHUB_OUTPUT
          echo "javadoc_version=${{ fromJson(matrix.versions).javadoc_version }}" | tee -a $GITHUB_OUTPUT
          echo "version=${{ fromJson(matrix.versions).version }}" | tee -a $GITHUB_OUTPUT
          echo "java_version=${{ fromJson(matrix.versions).java_version }}" | tee -a $GITHUB_OUTPUT

      - name: Set up JDK ${{ steps.manage-matrix.outputs.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.manage-matrix.outputs.java_version }}
          distribution: adopt

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache event files
        uses: actions/cache@v4
        id: cache-event-files
        with:
          path: src/main/java/com/tomacheese/eventfinder/listeners
          key: ${{ runner.os }}-eventfiles-${{ steps.manage-matrix.outputs.version }}

      - name: Create event files
        if: steps.cache-event-files.outputs.cache-hit != 'true'
        run: python tools/get-events.py ${{ steps.manage-matrix.outputs.javadoc_version }}

      - name: Build with Maven
        run: mvn package -Djava.version=${{ steps.manage-matrix.outputs.java_version }} -Dpapermc.groupId=${{ steps.manage-matrix.outputs.groupId }} -Dpapermc.version=${{ steps.manage-matrix.outputs.version }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.manage-matrix.outputs.version }}
          path: |
            target/*.jar

  finished:
    runs-on: ubuntu-latest
    needs: [get-versions, build]

    steps:
      - name: Finished
        run: echo finished
